In [1]:
import numpy as np
import pandas as pd
import sklearn
import gc
import functions
from imp import reload
reload(functions)

<module 'functions' from '/Users/monica/Project/mouse_atlas/notebooks/functions.py'>

In [4]:
expression  = pd.read_csv('../data/interim/mouse_atlas/mouse_atlas_expression.tsv', sep='\t', index_col=0)
genes       = pd.read_csv('../data/interim/mouse_atlas/mouse_atlas_genes.tsv', sep='\t', index_col=0)
annotations = pd.read_csv('../data/interim/mouse_atlas/mouse_atlas_samples.tsv', sep='\t', index_col=0)
annotations = annotations.rename(columns = {'Platform':'Platform_Category', 'Dataset Name': 'Dataset'})

In [6]:
# genes = functions.calculate_platform_dependence(blood_data, blood_annotations)

H_index_list, retained_genes_list = functions.resample_clustering(expression, annotations, resample_strategy='jackknife', n_resamples=1, n_clusters_list=[3,4,5,6,7,8])

Performing resampling upon data of shape: (14222, 1074)
Utlising 2500 genes as baseline expression data

Starting resampling

Omitting dataset ENCODE
Omitting dataset GGR
Omitting dataset Haemopedia-Mouse-RNAseq
Omitting dataset Immgen-ULI-RNAseq
Omitting dataset Haemopedia-microarray
Omitting dataset Gene-Expression-Commons
Omitting dataset Immgen-microarray
Omitting dataset Goodell
Omitting dataset Rossi
Omitting dataset Beerman
Omitting dataset Cabezas-Wallscheid
Omitting dataset Anandasabapathy
Omitting dataset Takata
Omitting dataset Martinez
Omitting dataset Mackay
Omitting dataset Doering
Omitting dataset Gautier
Omitting dataset Zigmond
Omitting dataset Tanaka
Omitting dataset Copley
Omitting dataset Mikkelsen
Omitting dataset Haniffa
Done



In [7]:
H_index_list

[array([0.727, 0.772, 0.899]),
 array([0.671, 0.824, 0.737, 0.899]),
 array([0.681, 0.752, 0.737, 0.899, 0.772]),
 array([0.5  , 0.539, 0.761, 0.833, 0.818, 0.495]),
 array([0.59 , 0.779, 0.796, 0.757, 0.681, 0.818, 0.636]),
 array([0.613, 0.802, 0.772, 0.757, 0.759, 0.818, 0.647, 0.707])]

In [11]:
# calculate the mean H_index of each number of cluster k 
for i in H_index_list:
    print( len(i), round(np.mean(i),3), round(min(i),2), round(max(i),2) )

3 0.799 0.73 0.9
4 0.783 0.67 0.9
5 0.768 0.68 0.9
6 0.658 0.5 0.83
7 0.722 0.59 0.82
8 0.734 0.61 0.82
